import { Club, Candidate, Application } from './types';

export const MOCK_CLUBS: Club[] = [
  {
    id: '1',
    name: 'AI 机器人实验室',
    category: '学术科技',
    description: '匹配您每周 4 小时的空闲时间以及对深度学习项目的浓厚兴趣。',
    memberCount: 128,
    growth: 24,
    icon: 'robot_2',
    matchScore: 98,
    tags: ['技术', '创新'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCExu-BJbOHkDpQN2TUYE6pjgT6lw0LA1-V8-xu_3qhlIMEneircVaegYWp_ROEL6_Yu8OVL4f7KU0r8-t7q9zMNNC-VzEySd3COzGRRat4Q8gCmbfJv0QpujaziwWpXO5tk-t6qqNsxy4kHIoTjgqTuhOt85_-WMmeBs_-UbZdSby0aCuJzSYIKIemdwoHCB5YQPe-PM10cU96CZZuWGFF0BJFchqhuHhUC6x5Bw2fUPaRP8PaouCIZqxBBZ9F2J73R8L6maxi3bKe',
    isTrending: true,
  },
  {
    id: '2',
    name: '数字艺术公社',
    category: '文化艺术',
    description: '与您的创意媒体副修背景及作品集技能高度契合。',
    memberCount: 328,
    growth: 12,
    icon: 'palette',
    matchScore: 92,
    tags: ['设计', 'UI/UX'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3OvW2KWwAcH5JRiUQprs3jqIWSWViPY81_i3_mqbaQKgXzDqOqZ4EZ2UtesqXSsRflZj4YcoprqZVw7BOe-q983iV-UF5ckrgPGsqVr6xYMVzIEM6npldc-r7RRZpmvDQgeG3Ie07MvmHztgX3hsrkcdKo36ITEL3YUM8b3pWv4FLBRO1ZB1QtwN1iECBY85Wur-lRDqVgHZGPlp2w7gtUl-hDTYW7WBMmecc58lg1pMKrZalHJgN6IgwY6rEb24P25KSj6Nlu03M',
  },
  {
    id: '3',
    name: '巅峰户外社',
    category: '体育竞技',
    description: '探索自然，挑战自我。',
    memberCount: 294,
    growth: 8,
    icon: 'hiking',
    tags: ['户外', '运动'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDINbn3IyoCku2qFL2CIwoMvbiwScVN2wJQWUIHgqfWvUOeNvaJFDRz8uqLOmRYxgzeloNqZahRuYiq5lFM--6x-Vw-JnXne1Q-y2ZouxlUdjpj1adar1ODseOvVPrx3fB_iYTPUoJAem5OKEAi9g2l8C9Y_gsP8OEQLoijwfJKSMz7-peImJDY7tFzM2dKMA0HmVx6MxjlhuNZuIYiaYMSeR7sGotHnw3T1MSeZkfznxd2U9L_G3rfwkxGrDGETtXBT-G6jGdYfL6c',
  },
  {
    id: '4',
    name: '绿色希望协会',
    category: '公益实践',
    description: '致力于校园环保与可持续发展，通过实践行动改变环境。',
    memberCount: 156,
    growth: 15,
    icon: 'eco',
    tags: ['环保', '公益'],
    image: 'https://picsum.photos/seed/green/800/600',
  },
  {
    id: '5',
    name: '创客空间',
    category: '创新创业',
    description: '将创意转化为现实的硬件实验室，提供 3D 打印与电路设计支持。',
    memberCount: 88,
    growth: 30,
    icon: 'build',
    tags: ['硬件', '创业'],
    image: 'https://picsum.photos/seed/maker/800/600',
  },
  {
    id: '6',
    name: '博雅辩论社',
    category: '文化艺术',
    description: '思辨明理，言语交锋。在这里磨练逻辑与表达。',
    memberCount: 112,
    growth: 5,
    icon: 'forum',
    tags: ['辩论', '逻辑'],
    image: 'https://picsum.photos/seed/debate/800/600',
  },
  {
    id: '7',
    name: '极客开发者联盟',
    category: '学术科技',
    description: '汇聚全校最顶尖的开发者，共同构建改变校园的开源项目。',
    memberCount: 85,
    growth: 18,
    icon: 'code',
    tags: ['编程', '开源'],
    image: 'https://picsum.photos/seed/geek/800/600',
  },
  {
    id: '8',
    name: '校篮球队',
    category: '体育竞技',
    description: '代表学校征战各大联赛，追求卓越与团队荣耀。',
    memberCount: 24,
    growth: 5,
    icon: 'sports_basketball',
    tags: ['篮球', '竞技'],
    image: 'https://picsum.photos/seed/basketball/800/600',
  },
  {
    id: '9',
    name: '爱心支教团',
    category: '公益实践',
    description: '利用寒暑假前往偏远地区，为那里的孩子带去知识与希望。',
    memberCount: 210,
    growth: 12,
    icon: 'school',
    tags: ['教育', '支教'],
    image: 'https://picsum.photos/seed/charity/800/600',
  },
  {
    id: '10',
    name: '商学院创业协会',
    category: '创新创业',
    description: '连接投资人与创业者，为你的商业计划提供专业辅导。',
    memberCount: 145,
    growth: 22,
    icon: 'business_center',
    tags: ['商业', '融资'],
    image: 'https://picsum.photos/seed/business/800/600',
  }
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: '1',
    name: '张思源',
    englishName: 'Sherry',
    school: '设计学院',
    major: '交互设计专业',
    year: '大二',
    skills: ['Figma', 'Motion Design', '沟通力'],
    score: 98,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCL6df-pVrm-Cw0KCgc2bxGYMLApBy0Rmo6H01p0po5CBqbLU3pj11T0qEczVMw49ugN0cuXzAJfOKd73ZL5vG5X_ljNG1OQXjSDtvIX1QPIAilZ_YOygqTQns0HyVq05Pn-5NBtfkBGfRuLkiXp0Ao-EvnNzvc1a_j07P3kUkNipZCQMRTwUrDBSaULCeDeu3iRxshGvko-vNgjKaMNORX9q635qz83PTg82HgZJbSZf3SAfyEwJUKvl5XOwqcripsaig3bqzNyZfT',
    isTopMatch: true,
  },
  {
    id: '2',
    name: '李恒',
    englishName: 'Henry',
    school: '信息工程学院',
    major: '软件工程',
    year: '大三',
    skills: ['Python', 'AI 算法', '团队协作'],
    score: 85,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDHCIDslVM_Y91fnrz9GSgXh26DWGwt5OTA1m7_GdnVfg3_3vSTJcGRdpnWfvOEZeAwhql6MbTx2nF7PEGbdHFfBQ3fkWuJ3qQyXipln_w820WPd8BrcHxlukv0OpaPfanJGgyy3z7TVoT3F_aZaZncTIVWzNs8U9F47LFlGB_FFca-O_PH6ez--BE9UI0BF6QKnERGPBF6epCHUMx3g5EmPHSc9X_5h-IotZeJxMrnknjXGXpFf3uUDhQwmqdJFOv9DtKMUakJzU0J',
  },
  {
    id: '3',
    name: '王妙',
    englishName: 'Mia',
    school: '新闻传播学院',
    major: '公共关系',
    year: '大一',
    skills: ['内容策划', '多媒体编辑', '英语专八'],
    score: 92,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgXx_KYApnbaVZLQPQ07DRwbY5TWvJt9DnqjXBYHEoiVT7mPSAM5k0hMILE6OzLD3_KmSg4aLUA34o1ksp39KW8ntaptXOQ1DYJnVhR_j06bi9886wCBL4KKx6uxSw6_Vdi7aqWEnnYwxYTwmV2wlmeGyp0UUMb-V9KfoIrdgvGkPBvV1_VE_ZmAW7v960S4tvauOwLl0HkAPnUKwairMNvQSvHc3eX_87nskOZP6_LeypQ-GTBrkcqEl9lSwJ4NYtALEuqkCZ2pyn',
  }
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    clubName: '极客俱乐部',
    clubIcon: 'rocket_launch',
    clubCategory: '学术科技',
    position: '全栈开发组员',
    status: 'admitted',
    lastUpdated: '2小时前',
  },
  {
    id: '2',
    clubName: '新浪潮艺术社',
    clubIcon: 'palette',
    clubCategory: '文化艺术',
    position: '视觉设计',
    status: 'interview',
    lastUpdated: '昨天',
  },
  {
    id: '3',
    clubName: '校篮球队',
    clubIcon: 'sports_basketball',
    clubCategory: '体育竞技',
    position: '前锋',
    status: 'rejected',
    lastUpdated: '3天前',
  }
];
